### ISSUE TITLE
Changed php7cc Version response breaks packet

### ISSUE THREAD

**Issue by HansVaider0815** [ManiacTwister/linter-php7cc#2]
At least in the current Version (1.1.0) of php7cc the output of `php7cc -V` is `PHP 7 Compatibility Checker 1.1.0` while this package checks for `PHP 7 Compatibility Checker Version 1.1.0`. So this package thinks php7cc isn't (correct) installed.

Solution: just update [The expected output](https://github.com/ManiacTwister/linter-php7cc/blob/master/lib/main.coffee#L17).

**Comment by ManiacTwister** [comment]
Thanks for your report, uploaded a fixed version
